### PR TITLE
changed the getallfeed to get-all-syncs with api resp

### PR DESCRIPTION
**Pull request by theharshguptaflutter**

### CODE REVIEW

**Review by hrithikwins — CHANGES_REQUESTED** [review]
getAllsync should be changed to getAllSyncs

**Comment by hrithikwins** [comment]
> getAllsync should be changed to getAllSyncs

@theharshguptaflutter

**Comment by hrithikwins** [comment]
@theharshguptaflutter changing this to camelCase is required, please change and commit here

**Comment by theharshguptaflutter** [comment]
already changed  @hrithikwins

**Pull request merged**
